### ISSUE TITLE
Update configuration for `misfit_preprocessor`

### ISSUE THREAD

**Issue by oyvindeide** [equinor/semeio#191]
For now we have two methods, spearman_correlation, the old default method, which does clustering and then PCA + scaling, and the new, auto-scale, which does PCA, clustering and then PCA + scaling. However the naming is a bit confusing (for example both use spearman but only one is named as such).

We also have the option of configuring `std_cutoff` and `alpha`, but only for `scaling`, when in fact that is more general, and should be global for the workflow. Or perhaps it should not be configurable at all?

**Comment by tralsos** [comment]
I think the "spearman" name is a bit confusing. What this job does is to cluster (based on correlations) and scale. But it is difficult for the user to parameterize, and I don't think it will be used much separately, except perhaps in research.  

So both methods do cluster + scale. The old one you should parameterize yourself and probably not use the default settings, while the "auto scale" is doing the parameterization for you.  So not sure I have a name suggestion, but something trying to capture "flexible cluster and scale" as opposed to "auto cluster and scale" where the latter we decided to call "MISFIT_PREPROCESSOR"

**Comment by oyvindeide** [comment]
After discussing with @tralsos we both agree that the name of the `spearman_correlation` method should change. We also discussed the option of configuring `alpha` and `std_cutoff` and how that should perhaps be moved out from `scaling`, as it is not really related to scaling in particular, but the data in general. The could be their own subsection, or perhaps be put together with `observations´, though they are not strictly related to the observations, but the simulated response. 

That might give something like this (all of this can be defaulted):

```
observations: 
    - obs_1
    - obs_2
ensemble_filtering:
    alpha: 2
    std_cutoff: 0.00001
clustering:
    method: auto_scale
    auto_scale:
        linkage:
            method: average
pca:
    threshold: 0.95
```

**Comment by lars-petter-hauge** [comment]
Looking at the PR and the proposition (in the PR). After some discussion with @oyvindeide I'm adding just getting something down on "paper"

From my understanding, the only difference between the auto_scale and spearman_correlation is that auto_scale does a PCA in advance which decides the input for the clustering. I think the configuration should reflect the difference. Considering the suggestion, the two methods looks to be much more separated than that.

```
workflow:
    auto_scale:  # optional, mutually exclusive with spearman_correlation
      clustering:  # optional
        hierarchical:  # optional, mutually exclusive with kmeans
            method: complete  # optional
            metric: jensenshannon  # optional
        kmeans:  # optional, mutually exclusive with hierarchical
      pca:  # optional
        threshold: 0.99    
    spearman_correlation:  # optional, mutually exclusive with auto_scale
        clustering:  # optional
           hierarchical:  # optional, mutually exclusive with kmeans
             method: centroid  # optional
             metric: dice  # optional
             criterion: maxclust  # optional
             t: 10  # optional
           kmeans:  # mutually exclusive with hierarchical
             some_option: 2
        pca:  # optional
           threshold: 0.98
```

I'm not sure if this is the best fit at all, but a suggestion at least. 

Providing your own clustering options (should be the same as going from `auto_scale` to `spearman_correlation`):

```
workflow:
      clustering:  # optional
        hierarchical:  # optional, mutually exclusive with kmeans
            method: complete  # optional
            metric: jensenshannon  # optional
            t: 10 # Default is auto
            criterion: maxclust # default maxclust
      pca:  # optional
        threshold: 0.99    
```

How to configure the auto_scale job:
```
workflow:
      clustering:  # optional
        hierarchical:  # optional, mutually exclusive with kmeans
            method: complete  # optional
            metric: jensenshannon  # optional
      pca:  # optional
        threshold: 0.99    
```
Also note that t: auto requires default option


So by specifying a value to the amount of clusters the user avoids the upfront PCA that is used to provide the cluster amount in the `auto_scale`. 

Issue: I am not sure how much we want to avoid users specifying those options, and this will make it "easier" to do so (hence easier to do a mistake?).

And the level `workflow` might not be needed either.

The autoscale job with kmeans:

```
clustering:  # optional
   kmeans:
      t: auto
pca:  # optional
   threshold: 0.99    
```

The spearm_man j.b with kmeans:

```
clustering:  # optional
   kmeans:
      t: 10
pca:  # optional
   threshold: 0.99    
```

I will look a bit more at it though, I might have overlooked a bit of complexity, and have not considered how it scales.
