### ISSUE TITLE
Auto correlation configuration

### ISSUE THREAD

**Issue by markusdregi** [equinor/semeio#67]
This is currently just me documenting my thought process...

However, what I would like to do is to get an overview of what can be configured related to the correlation workflows. Which of there parameters should be exposed via an `auto_correlation_workflow` and how this can be implemented in the current configuration system as well as in a future configuration system.

#### Current and requested workflow configuration
```yml
observation_scaling:
  calculate_keys:
    threshold: number
    std_cutoff: number
    alpha: number
    keys:
      -
        key: key_expr
        index: [1, 12, 16]

  update_keys:
    keys:
      -
        key: key_expr
        index: [1, 12, 16]

spearman_correlation:
  threshold: number
  observations: [WOPR_*, FOPR_*]
  fcluster:
    t: monocrit
    criterion: maxclust
    depth: 2
  linkage:
    method: complete
    pdist: euclidean
```

### Utilisation in current ERT configurations
In ERT configuration file:
```
LOAD_WORKFLOW ../bin/workflows/AUTO_CORRELATE_OBSERVATIONS
HOOK_WORKFLOW AUTO_CORRELATE_OBSERVATIONS PRE_UPDATE
```

../bin/workflows/AUTO_CORRELATE_OBSERVATIONS:
```
AUTO_CORRELATE_OBSERVATIONS ../input/data/auto_correlate_config.yml
```

../input/data/auto_correlate_config.yml:
```yml
correlation_method: spearman

spearman_correlation:
  threshold: number
  observations: [WOPR_*, FOPR_*]
  fcluster:
    t: monocrit
    criterion: maxclust
    depth: 2
  linkage:
    method: complete
    pdist: euclidean

observation_scaling:
  calculate_keys:
    threshold: number
    std_cutoff: number
    alpha: number
    keys:
      -
        key: key_expr
        index: [1, 12, 16]

  update_keys:
    keys:
      -
        key: key_expr
        index: [1, 12, 16]
```

Note that the above will not allow the users to edit the pipeline itself, but it will give them the possibility of configuring a predefined pipeline. We can support multiple methods for grouping observations, but they will all have to be implemented in semeio.

If research would like to implement their own correlation methods, they can either do so in a branch of semeio or by implementing a separate workflow that writes to the configuration file of `AUTO_CORRELATE_OBSERVATIONS` and specifically set `correlation_method: manual`.

A more native interaction with the pipeline (similarly to what can be done in the future in semeio) will have to wait for a new configuration file.

### Thoughts for integration with future ERT configuration
This is currently more or less a copy of my post in https://github.com/equinor/semeio/issues/47, but will hopefully evolve beyond that. The general idea would be to take the configuration file described above (`auto_correlate_config.yml`) and incorporate that as a native data element (record) in the future ERT configuration file. In that manner one can transfer from an old setup to a new setup by putting the configuration files inside the ERT config and use the `auto_correlate_observations` as one of the stages in the `model_update_pipeline`.

This will allow us to implement a first iteration of a pipeline language that we can use in ERT and getting some usage without immediately exposing it to our users. In general I want a language where I can define records and pipe them to data processing units (either Python functions or stages (a sequence of python functions). These processing units are then again to output records that can be passed to other processing units. More details below.

I think this would be a great first demonstration of a stage of a model updating pipeline that could later be lifted into the general ERT configuration file. In the end, what I would like to see is a data pipeline to describe the updating of a model in a classical pipes and filter design.

I'll refer to the main pipeline as the model updating pipeline, which consists of multiple stages. Each stage again can define input and output records (data streams), records local to the scope of the stage and a pipeline. Each stage pipeline consists of a list of functions that is to carry out a particular task and is implemented in Python. Each function can have records local to their scope.

The records input to the model updating pipeline at large would be the `parameters`, `simulation_results` and `observations`. All of which records consists of a set of original data, together with a set of filters that are to be applied to the original data. A filter could for instance be a describing a subset of the observations together with a scalar that is to be applied to the errors or a subset of the realisations that are considered active etc. In this manner one can describe edits to the underlying data without changing the data itself.

I would then like the user to be able to describe the updating pipeline as follows:
```yml
model_update:
  records:
    es_mda_weights: [4, 2, 1]

  pipeline:
    - auto_correlate_observations(threshold: 0.4)
    - es_mda(es_mda_weights) # or equivalently "es_mda(weights: [4, 2, 1])"
```

Then one can define each of the stages in a stages section (either in a site-configuration or in project or experiment configuration):

```yml
stages:
  auto_correlate_observations:
    input:
      - observations
      - simulated_data
      - threshold -> 0.7 # default to 0.7

    output:
      - observations
      - simulated_data

    records:
      spearman_setup:
        fcluster:
          t: monocrit
          criterion: maxclust
          depth: 2
        linkage:
          method: complete

    pipeline:
      - spearman_correlation(spearman_setup)
      - correlated_observation_scaling(my_super_constant: 0.1)
```

The reason to explicitly name the input and output of each stage is that by doing so, we can ensure that only the output records are added to the global records after the stage. We can also track and validate that records will be available at the time when needed. In addition, this allows for parallelisation of the pipeline where it is possible; running multiple stages simultaneously.

Now, we could initiate this bigger scheme of things here by supporting specifying a single stage, namely the `auto_correlate_observations` and then we could for now allow users to access it via the old ERT configuration by running it as a workflow, i.e. 

`HOOK_WORKFLOW auto_correlate_observations PRE_UPDATE`
